---
# SPDX-License-Identifier: AGPL-3.0-or-later
version: '3'
services:
  web:
    image: icinga/icingaweb2
    ports:
      - 8484:8080
    environment:
      icingaweb.enabledModules: whoarewe
      icingaweb.passwords.icingaweb2.icingaadmin: icinga
      icingaweb.passwords.icingaweb2.player1: '123456'
      icingaweb.passwords.icingaweb2.player2: '123456'
      icingaweb.passwords.icingaweb2.player3: '123456'
      icingaweb.passwords.icingaweb2.player4: '123456'
      icingaweb.authentication.icingaweb2.backend: db
      icingaweb.authentication.icingaweb2.resource: icingaweb_db
      icingaweb.config.global.config_backend: db
      icingaweb.config.global.config_resource: icingaweb_db
      icingaweb.config.logging.log: php
      icingaweb.groups.icingaweb2.backend: db
      icingaweb.groups.icingaweb2.resource: icingaweb_db
      icingaweb.modules.whoarewe.config.redis.host: redis
      icingaweb.resources.icingaweb_db.type: db
      icingaweb.resources.icingaweb_db.db: mysql
      icingaweb.resources.icingaweb_db.host: db
      icingaweb.resources.icingaweb_db.dbname: web
      icingaweb.resources.icingaweb_db.username: web
      icingaweb.resources.icingaweb_db.password: web
      icingaweb.resources.icingaweb_db.charset: utf8mb4
      icingaweb.roles.Administrators.users: icingaadmin
      icingaweb.roles.Administrators.permissions: '*'
      icingaweb.roles.Gamers.users: player1,player2,player3,player4
      icingaweb.roles.Gamers.permissions: module/whoarewe
    volumes:
      - web:/data
      - ./:/usr/share/icingaweb2/modules/whoarewe:ro
  db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  web: { }
  db: { }
  redis: { }
